CREATE TABLE IF NOT EXISTS paciente
(
  id BIGINT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(250) NOT NULL,
  cpf VARCHAR(250) NOT NULL,
  idade VARCHAR(250) NOT NULL,
  telefone VARCHAR(250) NULL,
  PRIMARY KEY (ID)
);